services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - /Users/JarnoB/Documents/data/occassio/indices/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - es-net
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 4GB

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.12.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601


  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      ES_URI: es-container
    ports:
      - 80:5000
    networks:
      - es-net

networks:
  es-net:
    driver: bridge
