name: ESLint

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/browser
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
